# This workflow was added by CodeSee. Learn more at https://codesee.io/
on:
  push:
    branches:
      - main
      - dev
  pull_request_target:
    types: [opened, synchronize, reopened]

name: CodeSee

permissions: read-all

jobs:
  codesee:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Analyze the repo with CodeSee
    steps:
      - uses: Codesee-io/codesee-action@91e875f4ae6459ebca8797da57bf61a4eba1b853 # v2
        with:
          codesee-token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
